FROM xray-demo-docker-virtual.jfrog.io/hello-world:latest
MAINTAINER Stanley Fong stanleyf@jfrog.com
add commons-io-2.4.jar .
add commons-9.11.jar .
add commons-4.69.jar .
ENV TEST_XRAY=/usr/local/bin
